version: "3.8"
services:
    app:
        build:
            args:
                user: shabit
                uid: 1000
            context: ./
            dockerfile: Dockerfile
        image: lsapp
        container_name: laravel-blog-app
        restart: unless-stopped
        working_dir: /var/www/
        volumes:
          - ./:/var/www
        networks:
          - lsapp
    
    localhost:
        image: mysql:5.7
        container_name: laravel-blog-app-db
        restart: unless-stopped
        environment:
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
            #MYSQL_PASSWORD: ${DB_PASSWORD}
            #MYSQL_USER: ${DB_USERNAME}
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        volumes:
            - ./docker-compose/data/mysql:/var/lib/mysql
            - ./docker-compose/mysql:/docker-entrypoint-initdb.d
        networks:
            - lsapp

    phpmyadmin:
        image: phpmyadmin
        restart: always
        ports:
            - 8080:80
        environment:
            PMA_ARBITRARY: 1
            PMA_HOST: db
            PMA_PORT: 3306
            PMA_USER: ${DB_USERNAME}
            PMA_PASSWORD: ${DB_PASSWORD}
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        networks:
            - lsapp

    nginx:
        image: nginx:1.17-alpine
        container_name: laravel-blog-app-nginx
        restart: unless-stopped
        ports:
            - 8000:80
        volumes:
            - ./:/var/www
            - ./docker-compose/nginx:/etc/nginx/conf.d
        networks:
            - lsapp

networks:
    lsapp:
        driver: bridge